apiVersion: v1
kind: ConfigMap
metadata:
  name: nestjs-backend-config
  namespace: nestjs-backend
data:
  APP_PORT: "5000"
  LOG_LEVEL: "info"
  LOG_ENABLE_LOG_TO_FILE: "true"
  LOG_ROOT_FOLDER: "/app/logs"
  LOG_MAX_FILES: "10"
  LOG_MAX_SIZE: "10000000"
