apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nestjs-backend-db-credentials
  namespace: nestjs-backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: nestjs-backend-db-credentials
  data:
    - secretKey: host
      remoteRef:
        key: nestjs-backend-dev/rds-credentials
        property: host
    - secretKey: port
      remoteRef:
        key: nestjs-backend-dev/rds-credentials
        property: port
    - secretKey: database
      remoteRef:
        key: nestjs-backend-dev/rds-credentials
        property: database
    - secretKey: username
      remoteRef:
        key: nestjs-backend-dev/rds-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: nestjs-backend-dev/rds-credentials
        property: password
