apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nestjs-backend
resources:
  - namespace.yaml
  - configmap.yaml
  - external-secrets.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - network-policy.yaml
